### ISSUE TITLE
OOM Java heap space on start up

### ISSUE THREAD

**Issue by hsrinara** [nikitabobko/gcal-notifier-kotlin-gtk#11]
Hi @nikitabobko, when launching the application I see this exception below. Is there a way to increase the heap space for your application?

```Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:633)
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:392)
	at java.base/java.io.StringWriter.write(StringWriter.java:122)
	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:590)
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:418)
	at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:406)
	at com.google.gson.internal.bind.TypeAdapters$16.write(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at com.google.gson.Gson.toJson(Gson.java:618)
	at ru.nikitabobko.gcalnotifier.support.JsonUserDataManager.safe(UserDataManager.kt:68)
	at ru.nikitabobko.gcalnotifier.support.JsonUserDataManager.safeEventsList(UserDataManager.kt:47)
	at ru.nikitabobko.gcalnotifier.support.JsonUserDataManager.safe(UserDataManager.kt:43)
	at ru.nikitabobko.gcalnotifier.controller.ControllerImpl$refresh$1.invoke(Controller.kt:146)
	at ru.nikitabobko.gcalnotifier.controller.ControllerImpl$refresh$1.invoke(Controller.kt:71)
	at ru.nikitabobko.gcalnotifier.support.GoogleCalendarManagerImpl$getUpcomingEventsAsync$1.invoke(GoogleCalendarManager.kt:85)
	at ru.nikitabobko.gcalnotifier.support.GoogleCalendarManagerImpl$getUpcomingEventsAsync$1.invoke(GoogleCalendarManager.kt:43)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by nikitabobko** [comment]
Thank you for your report! It's good to know that in some cases current heap size is not enough. You can change heap size in /usr/bin/gcal-notifier-kotlin-gtk

**Comment by hsrinara** [comment]
It seems to fail in the implementation of the gson bit when converting to json. I wonder whether there is a mechanism to stream the json out bit by bit. 

Perhaps the UserDataManager.safeEventsList can be made to write each element one by one.

**Comment by hsrinara** [comment]
and just FYI, when I bumped the memory, I managed to write the events file: 

-rw-rw-r-- 1 hsrinara hsrinara 600K Mar 27 09:19 /home/hsrinara/.config/gcal-notifier-kotlin-gtk/events.json

And just confirmed I now have the events popping up on my screen. Thanks for your fast response @nikitabobko

**Comment by nikitabobko** [comment]
Can I ask you to try [2.0.9-SNAPSHOT](https://drive.google.com/open?id=10bYXnPRkF7GVb2Og-B5O6dtqaVQR8q5r) version (or you can build SNAPSHOT by yourself from `master` branch). I've applied your suggestion to use stream to work with Gson and want to know whether it helps in your case. Thanks!

**Comment by hsrinara** [comment]
```Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4030)
	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base/java.lang.String.substring(String.java:1846)
	at com.google.api.client.util.DateTime.parseRfc3339(DateTime.java:315)
	at com.google.api.client.util.Data.parsePrimitiveValue(Data.java:439)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:859)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:472)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:781)
	at com.google.api.client.json.JsonParser.parseArray(JsonParser.java:648)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:740)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:472)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:781)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:382)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:355)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
	at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at ru.nikitabobko.gcalnotifier.support.GoogleCalendarManagerImpl.getUpcomingEvents(GoogleCalendarManager.kt:69)
	at ru.nikitabobko.gcalnotifier.support.GoogleCalendarManagerImpl.access$getUpcomingEvents(GoogleCalendarManager.kt:43)
	at ru.nikitabobko.gcalnotifier.support.GoogleCalendarManagerImpl$getUpcomingEventsAsync$1.invoke(GoogleCalendarManager.kt:82)
	at ru.nikitabobko.gcalnotifier.support.GoogleCalendarManagerImpl$getUpcomingEventsAsync$1.invoke(GoogleCalendarManager.kt:43)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by hsrinara** [comment]
Apologies for the terse response, I was swamped this morning. Responding from mobile so my analysis might be a little wrong. 

Couple of thoughts. 
 * It appears to be throwing when loading the events from disk now. 

 * I don't know gtk or the UI framework you have used so don't know if a blocking call is necessary but this API on View here is a problem for our memory issue. It forces you collect up all events to be passed to the UI later. If you can change this API to have a stream of events somehow, then that's one way to fix this. However, I suspect the UI widgets won't expose a steaming API. 
fun​ ​update​(​events​:​ ​List​<​MyEvent​>). 

* Another approach is to do an n way merge sort with files as your external buffer so you don't need to load everything into memory. If you notice, in the UI layer most events are dropped anyway because it's beyond the maximum number of events to render configuration. This solution would also require that filtering to be done on the backend after the n way merge sort. Then the call to the view is very small. That's probably the solution I would go for.

**Comment by hsrinara** [comment]
Another approach would be to do the sorting and filtering onto the Google calendar backend if it supports those functions so not as much is retrieved.
